name: mid-west-coast-AZ-NV
start_date: 2020-01-31
end_date: 2020-10-01
dt: 0.25
dynfilter_path: data/west-coast-AZ-NV/filtergithub.txt

spatial_setup:
  base_path: data/west-coast-AZ-NV

  setup_name: west-coast-AZ-NV
  geodata: geodata.csv
  mobility: mobility.txt
  popnodes: pop2010

interventions:
  scripts_path: COVIDScenarioPipeline/NPI

parameters_seir:
  sigma: 1 / 5.2
  gamma:
    distribution: uniform
    low: 1 / 6
    high: 1 / 2.6
  R0s:
    distribution: uniform
    low: 2
    high: 3
