name: mid-west-coast-AZ-NV
start_date: 2020-01-31
end_date: 2020-10-01
nsimulations: 1000
dt: 0.25
dynfilter_path: data/west-coast-AZ-NV/filtergithub.txt
report_location_name: California

spatial_setup:
  base_path: data/west-coast-AZ-NV
  setup_name: west-coast-AZ-NV
  geodata: geodata.csv
  mobility: mobility.txt
  popnodes: pop2010
  include_in_report: targeted

interventions:
  scripts_path: COVIDScenarioPipeline/NPI
  scenarios:
    - Wuhan
    - None
    - KansasCity
  settings:
    Wuhan:
      begin: 2020/03/19
      end: 2020/05/14
      upper: 0.89
      lower: 0.81
    None:
    KansasCity:
      begin: 2020/03/19
      end: 2020/05/14
      upper: 0.65
      lower: 0.44

seir:
  parameters:
    sigma: 1 / 5.2
    gamma:
      distribution: uniform
      low: 1 / 6
      high: 1 / 2.6
    R0s:
      distribution: uniform
      low: 2
      high: 3

hospitalization:
  paths:
    output_path: hospitalization
  parameters:
    time_hosp: [1.23, 0.79]
    time_disch: [log(11.5), log(1.22)]
    time_death: [log(11.25), log(1.15)]
    time_ICU: [log(8.25), log(2.2)]
    time_ICUdur: [log(17.46), log(4.044)]
    time_vent: [log(10.5), log((10.5-8)/1.35)]
    mean_inc: 5.2
    dur_inf_shape: 2
    dur_inf_scale: 3
    end_date: 2020-10-01
    p_death: [.0025, .005, .01]
    p_death_rate: 0.1
    p_ICU: 0.264
    p_vent: 0.15

report:
  paths:
    scenario_output_paths: ["unifiedKansasCity", "unifiedWuhan", "unifiedNPI"]
    shapefile_fn: counties_2010_west-coast-AZ-NV.shp
  data_settings:
    pop_year: 2010
  plot_settings:
    plot_intervention: TRUE
  formatting:
    scenario_labels_short: ["KC", "WH", "UC"]
    scenario_labels: ["Pre-Lockdown-like","Wuhan/Lockdown-like","Worst Case Uncontrolled"]
    scenario_colors: ["#D95F02", "#1B9E77", "#7570B3"]
    pdeath_level: ["low", "med", "high"]
    pdeath_labels: ["0.25% IFR", "0.5% IFR", "1% IFR"]



