name: mid-west-coast-AZ-NV
start_date: 2020-01-31
end_date: 2020-10-01
nsimulations: 1000
dt: 0.25
dynfilter_path: data/west-coast-AZ-NV/filtergithub.txt

spatial_setup:
  base_path: data/west-coast-AZ-NV

  setup_name: west-coast-AZ-NV
  geodata: geodata.csv
  mobility: mobility.txt
  popnodes: pop2010
  include_in_report: targeted

interventions:
  scenarios:
    - Wuhan
    - None
    - KansasCity
    - SC
    - Scenario1
    - Scenario2
  settings:
    None:
      template: ReduceR0
      period_start_date: 2020-04-01
      period_end_date: 2020-05-15
      value:
        distribution: fixed
        value: 0
    Wuhan:
      template: ReduceR0
      period_start_date: 2020-04-01
      period_end_date: 2020-05-15
      value:
        distribution: uniform
        low: .14
        high: .33
    KansasCity:
      template: ReduceR0
      period_start_date: 2020-04-01
      period_end_date: 2020-05-15
      value:
        distribution: uniform
        low: .04
        high: .23
    SC:
      template: ReduceR0
      period_start_date: 2020-03-13
      value:
        distribution: truncnorm
        a: 0.16
        b: 0.30
        mean: 0.18
        sd: 0.05
    Scenario1:
      template: Stacked
      scenarios:
        - Wuhan
        - SC
    Scenario2:
      template: Stacked
      scenarios:
        - template: ReduceR0
          period_start_date: 2020-03-01
          period_end_date: 2020-03-09
          value:
            distribution: uniform
            low: .14
            high: .33
        - SC
        - template: ReduceR0
          period_start_date: 2020-03-15
          period_end_date: 2020-05-25
          value:
            distribution: uniform
            low: .14
            high: .33

seir:
  parameters:
    sigma: 1 / 5.2
    gamma:
      distribution: uniform
      low: 1 / 6
      high: 1 / 2.6
    R0s:
      distribution: uniform
      low: 2
      high: 3

hospitalization:
  paths:
    output_path: hospitalization
  parameters:
    time_hosp: [1.23, 0.79]
    time_disch: [log(11.5), log(1.22)]
    time_death: [log(11.25), log(1.15)]
    time_ICU: [log(8.25), log(2.2)]
    time_ICUdur: [log(17.46), log(4.044)]
    time_vent: [log(10.5), log((10.5-8)/1.35)]
    mean_inc: 5.2
    dur_inf_shape: 2
    dur_inf_scale: 3
    end_date: 2020-10-01
    p_death: [.0025, .005, .01]
    p_death_rate: 0.1
    p_ICU: 0.264
    p_vent: 0.15
