name: mid-west-coast-AZ-NV
start_date: 2020-01-31
end_date: 2020-10-01
nsimulations: 1000
dt: 0.25
dynfilter_path: data/west-coast-AZ-NV/filtergithub.txt
report_location_name: California

spatial_setup:
  base_path: data/west-coast-AZ-NV
  setup_name: west-coast-AZ-NV
  geodata: geodata.csv
  shapefile_name: shp/counties_2010_west-coast-AZ-NV.shp
  shapefile: shp/counties_2010_west-coast-AZ-NV.shp # Two is redundant.  We should fix this
  mobility: mobility.txt
  popnodes: pop2010
  nodenames: geoid  # Name of the column in geodata with uniquely name of nodes
  include_in_report: targeted

importation:
  census_api_key: "DO NOT PUT THE KEY IN  THE PUBLIC REPO"
  travel_dispersion: 3
  maximum_destinations: Inf
  dest_type : state
  dest_country : USA
  aggregate_to: airport
  cache_work: TRUE
  update_case_data: TRUE
  draw_travel_from_distribution: FALSE
  print_progress: FALSE
  travelers_threshold: 10000
  airport_cluster_distance: 80
  param_list:
    incub_mean_log: log(5.89)
    incub_sd_log: log(1.74)
    inf_period_nohosp_mean: 15
    inf_period_nohosp_sd: 5
    inf_period_hosp_shape: 0.75
    inf_period_hosp_scale: 5.367
    p_report_source: [0.05, 0.25]
    shift_incid_days: -10
    delta: 1

#seeding:
#  method: FolderDraw
#  folder_path: model_output/importation/

seeding:
  method: PoissonDistributed
  lambda_file: data/west-coast-AZ-NV/seeding.csv

interventions:
  scenarios:
    - Wuhan
    - None
    - Influenza1918
    - SchoolClosure
    - TestIsolate
    - CaliforniaMild
    - CaliforniaMid
    - CaliforniaSevere
  settings:
    None:
      template: ReduceR0
      period_start_date: 2020-01-31
      period_end_date: 2020-03-13   
      value:
        distribution: fixed
        value: 0
    Wuhan:
      template: ReduceR0
      period_start_date: 2020-03-19
      period_end_date: 2020-05-14
      value:
        distribution: uniform
        low: .81
        high: .89
    Influenza1918:
      template: ReduceR0
      period_start_date: 2020-05-15
      period_end_date: 2020-10-01
      value:
        distribution: uniform
        low: .44
        high: .65
    SchoolClosure:
      template: ReduceR0
      period_start_date: 2020-03-13
      period_end_date: 2020-03-19
      value:
        distribution: truncnorm
        a: 0.16
        b: 0.30
        mean: 0.18
        sd: 0.05
    TestIsolate:
      template: ReduceR0
      period_start_date: 2020-05-15
      period_end_date: 2020-10-01
      value:
        distribution: uniform
        low: .48
        high: .76
    CaliforniaMild:
      template: Stacked
      scenarios:
        - SchoolClosure
        - Wuhan
    CaliforniaSevere:
      template: Stacked
      scenarios:
        - SchoolClosure
        - Wuhan
        - TestIsolate
    CaliforniaMid:
      template: Stacked
      scenarios:
        - SchoolClosure
        - Wuhan
        - Influenza1918

seir:
  parameters:
    sigma: 1 / 5.2
    alpha:
      distribution: fixed
      value: 1
    gamma:
      distribution: uniform
      low: 1 / 6
      high: 1 / 2.6
    R0s:
      distribution: uniform
      low: 2
      high: 3

hospitalization:
  paths:
    output_path: hospitalization
  parameters:
    time_hosp: [1.23, 0.79]
    time_disch: [log(11.5), log(1.22)]
    time_death: [log(11.25), log(1.15)]
    time_ICU: [log(8.25), log(2.2)]
    time_ICUdur: [log(16), log(2.96)]
    time_vent: [log(10.5), log((10.5-8)/1.35)]
    p_death: [.0025, .005, .01]
    p_death_names: ["low","med","high"]
    p_death_rate: 0.1
    p_ICU: 0.32
    p_vent: 0.15

report:
  data_settings:
    pop_year: 2010
  plot_settings:
    plot_intervention: TRUE
  formatting:
    scenario_labels_short: ["WH","UC","1918","SC","TI","M1","M2","M3"]
    scenario_labels:
    - Wuhan/Lockdown
    - Worst Case Uncontrolled
    - Influenza 1918
    - School Closure
    - Test and Isolate
    - Mild Proposed Scenario
    - Moderate Proposed Scenario
    - Severe Proposed Scenario
    scenario_colors: ["#D95F02", "#1B9E77", "#7570B3", "#7570B3", "#7570B3", "#7570B3", "#7570B3", "#7570B3"]
    pdeath_labels: ["0.25% IFR", "0.5% IFR", "1% IFR"]
    display_dates: ["2020-5-1", "2020-7-1", "2020-9-1"]
