install.packages("devtools")
require(devtools)

repo_url <- "https://cran.rstudio.com"

# TODO: better than nothing, but this doesn't handle package dependencies (use packrat)
install_version("rgdal", version = "1.4-8", repos = repo_url)
install_version("doParallel", version = "1.0.14", repos = repo_url)
install_version("tidyr", version = "1.0.2", repos = repo_url)
install_version("dplyr", version = "0.8.3", repos = repo_url)
install_version("readr", version = "1.3.1", repos = repo_url)
install_version("ggplot2", version = "3.2.0", repos = repo_url)
install_version("gridExtra", version = "2.3", repos = repo_url)
install_version("viridis", version = "0.5.1", repos = repo_url)
install_version("ggfortify", version = "0.4.8", repos = repo_url)
install_version("flextable", version = "0.5.9", repos = repo_url)
install_version("tidyverse", version = "1.2.1", repos = repo_url)
install_version("truncnorm", version = "1.0-8", repos = repo_url)
install_version("geosphere", version = "1.5-7", repos = repo_url)
install_version("ggpubr", version = "0.2.5", repos = repo_url)
install_version("ggvoronoi", version = "0.8.2", repos = repo_url)
install_version("gpclib", version = "1.5-5", repos = repo_url)
install_version("igraph", version = "1.2.4.2", repos = repo_url)
install_version("maptools", version = "0.9-8", repos = repo_url)
install_version("raster", version = "3.0-7", repos = repo_url)
install_version("rlist", version = "0.4.6", repos = repo_url)
install_version("cowplot", version = "1.0.0", repos = repo_url)
install_version("tidycensus", version = "0.9.5", repos = repo_url)
install_version("yaml", version = "2.2.1", repos = repo_url)
install_version("optparse", version = "1.6.4", repos = repo_url)
install_version("lubridate", version = "1.7.4", repos = repo_url)
install_version("sf", version = "0.8-1", repos = repo_url)
install_version("splines2", version = "0.2.8", repos = repo_url)
install_version("nnls", version = "1.4", repos = repo_url)

install_github("HopkinsIDD/globaltoolboxlite")
install_github("HopkinsIDD/covidImportation", ref = "v1.6")

# Install arrow and it's extra dependencies
install_version("arrow", version = "0.16.0.2", repos = repo_url)
arrow::install_arrow()
