#!/bin/bash
#SBATCH --nodes 1                      # Node PER JOB. Apparently this works on MARC
#SBATCH --ntasks-per-node 1            # MPI sense -> just 1.
#SBATCH --cpus-per-task 1              # No more than the number of CPU in a node. CPU <- coeur dans slurm
# #SBATCH --qos=week                     # Echo is authorized to launch week-long job
# #SBATCH --reservationname=COVID19

set -x

curl \
  -H "Title: $COVID_RUN_INDEX Done ✅" \
  -H "Priority: urgent" \
  -H "Tags: warning,snail" \
  -d "TODO say how many failure and stuff" \
  ntfy.sh/flepimop_alerts

# get the slack credentials
source slack_credentials.sh # populate $SLACK_TOKEN