

# Extract the age-stratified Population and IFR estimates for the Country/Location of interest.
#  - the base data is generated by the COVID19_IFR repo which pulls data from Worldpop based on tiffs and shapefiles.


# Country ISO
iso_of_interest <- "KOR"


# SETUP -------------------------------------------------------------------
library(tidyverse)



# LOAD BASE DATA ----------------------------------------------------------

# Save as parquets (removing CSVs for size)
# global_pop_5yr <- read_csv("data/ifr_and_pop/GLOBAL_age_pop_5yr.csv") %>% rename(age = age_group) 
# arrow::write_parquet(global_pop_5yr, "data/ifr_and_pop/GLOBAL_age_pop_5yr.parquet")
# global_pop_1yr <- read_csv("data/ifr_and_pop/GLOBAL_age_pop_data.csv") %>% select(-loc) %>% separate(age, into=c("age_l","age_r"), sep="_", remove = FALSE)
# arrow::write_parquet(global_pop_5yr, "data/ifr_and_pop/GLOBAL_age_pop_1yr.parquet")
# global_ifr_adm2 <- read_csv("data/ifr_and_pop/GLOBAL_ifr_ageadj.csv")
# arrow::write_parquet(global_ifr_adm2, "data/ifr_and_pop/GLOBAL_ifr_ageadj_adm2.parquet")
# global_ifr_adm1 <- read_csv("data/ifr_and_pop/GLOBAL_ifr_ageadj_adm1.csv")
# arrow::write_parquet(global_ifr_adm1, "data/ifr_and_pop/GLOBAL_ifr_ageadj_adm1.parquet")
# global_ifr_adm0 <- read_csv("data/ifr_and_pop/GLOBAL_ifr_ageadj_adm0.csv")
# arrow::write_parquet(global_ifr_adm0, "data/ifr_and_pop/GLOBAL_ifr_ageadj_adm0.parquet")


global_pop_5yr <- arrow::read_parquet("data/ifr_and_pop/GLOBAL_age_pop_5yr.parquet")
global_pop_1yr <- arrow::read_parquet("data/ifr_and_pop/GLOBAL_age_pop_1yr.parquet")
global_ifr_adm2 <- arrow::read_parquet("data/ifr_and_pop/GLOBAL_ifr_ageadj_adm2.parquet")
global_ifr_adm1 <- arrow::read_parquet("data/ifr_and_pop/GLOBAL_ifr_ageadj_adm1.parquet")
global_ifr_adm0 <- arrow::read_parquet("data/ifr_and_pop/GLOBAL_ifr_ageadj_adm0.parquet")



# SUBSET TO SPECIFIED LOCATION --------------------------------------------
# -- current setup is just for Country subsets. For state or other, need to modify on your own

loc_pop_5yr <- global_pop_5yr %>% filter(adm0 == iso_of_interest) 
loc_pop_1yr <- global_pop_1yr %>% filter(adm0 == iso_of_interest) 
loc_ifr_adm2 <- global_ifr_adm2 %>% filter(adm0 == iso_of_interest) 
loc_ifr_adm1 <- global_ifr_adm1 %>% filter(adm0 == iso_of_interest) 
loc_ifr_adm0 <- global_ifr_adm0 %>% filter(adm0 == iso_of_interest)  



# SAVE LOCATION DATA ------------------------------------------------------

arrow::write_parquet(loc_pop_5yr, paste0("data/ifr_and_pop/", iso_of_interest, "_age_pop_5yr.parquet"))
arrow::write_parquet(loc_pop_1yr, paste0("data/ifr_and_pop/", iso_of_interest, "_age_pop_1yr.parquet"))
arrow::write_parquet(loc_ifr_adm2, paste0("data/ifr_and_pop/", iso_of_interest, "_ifr_ageadj_adm2.parquet"))
arrow::write_parquet(loc_ifr_adm1, paste0("data/ifr_and_pop/", iso_of_interest, "_ifr_ageadj_adm1.parquet"))
arrow::write_parquet(loc_ifr_adm0, paste0("data/ifr_and_pop/", iso_of_interest, "_ifr_ageadj_adm0.parquet"))





